CREATE TABLE IF NOT EXISTS languages
(
    id   VARCHAR(3) PRIMARY KEY,
    name varchar(100)
);

INSERT INTO languages (id, name)
SELECT *
FROM (VALUES ('eng', 'English'),
             ('ger', 'Deutsch'),
             ('fre', 'Français'),
             ('spa', 'Español'),
             ('rus', 'Русский язык'),
             ('chi', 'Chinese'),
             ('ita', 'Italian'),
             ('jpn', 'Japanese'),
             ('por', 'Portuguese'),
             ('ara', 'Arabic'),
             ('kor', 'Korean'),
             ('pol', 'Polish'),
             ('heb', 'Hebrew'),
             ('dut', 'Dutch'),
             ('lat', 'Latin'),
             ('ind', 'Indonesian'),
             ('und', 'Undetermined'),
             ('swe', 'Swedish'),
             ('tur', 'Turkish'),
             ('cmn', 'Mandarin'),
             ('hin', 'Hindi'),
             ('urd', 'Urdu'),
             ('hun', 'Hungarian'),
             ('dan', 'Danish'),
             ('cze', 'Czech'),
             ('ukr', 'Ukrainian'),
             ('per', 'Persian'),
             ('gre', 'Greek'),
             ('rum', 'Romanian'),
             ('bul', 'Bulgarian'),
             ('vie', 'Vietnamese'),
             ('cat', 'Catalan'),
             ('ben', 'Bengali'),
             ('tha', 'Thai'),
             ('mul', 'Multiple languages'),
             ('nor', 'Norwegian'),
             ('fin', 'Finnish'),
             ('tam', 'Tamil'),
             ('scr', 'Croatian'),
             ('guj', 'Gujarati'),
             ('wel', 'Welsh'),
             ('mar', 'Marathi'),
             ('tib', 'Tibetan'),
             ('yid', 'Yiddish'),
             ('pan', 'Panjabi'),
             ('arm', 'Armenian'),
             ('scc', 'Serbian'),
             ('tel', 'Telugu'),
             ('may', 'Malay'),
             ('kan', 'Kannada'),
             ('slo', 'Slovak'),
             ('srp', 'Serbian'),
             ('san', 'Sanskrit'),
             ('slv', 'Slovenian'),
             ('mal', 'Malayalam'),
             ('alb', 'Albanian'),
             ('bur', 'Burmese'),
             ('lit', 'Lithuanian'),
             ('lav', 'Latvian'),
             ('nep', 'Nepali'),
             ('mon', 'Mongolian'),
             ('est', 'Estonian'),
             ('afr', 'Afrikaans'),
             ('geo', 'Georgian'),
             ('mac', 'Macedonian'),
             ('ori', 'Oriya'),
             ('hrv', 'Croatian'),
             ('grc', 'Ancient Greek'),
             ('iri', 'Irish'),
             ('bel', 'Belarusian'),
             ('ice', 'Icelandic'),
             ('kur', 'Kurdish'),
             ('snd', 'Sindhi'),
             ('uzb', 'Uzbek'),
             ('ota', 'Turkish, Ottoman'),
             ('aze', 'Azerbaijani'),
             ('bos', 'Bosnian'),
             ('pus', 'Pushto'),
             ('kaz', 'Kazakh'),
             ('snh', 'Sinhalese'),
             ('sin', 'Sinhalese'),
             ('amh', 'Amharic'),
             ('asm', 'Assamese'),
             ('swa', 'Swahili'),
             ('tgk', 'Tajik '),
             ('glg', 'Galician '),
             ('gag', 'Galician'),
             ('kir', 'Kyrgyz'),
             ('gle', 'Irish'),
             ('baq', 'Basque'),
             ('gae', 'Scottish Gaelix'),
             ('tgl', 'Tagalog'),
             ('raj', 'Rajasthani'),
             ('lao', 'Lao'),
             ('jav', 'Javanese'),
             ('khm', 'Khmer'),
             ('tat', 'Tatar'),
             ('roh', 'Raeto-Romance'),
             ('enm', 'English, Middle (1100-1500)'),
             ('hau', 'Hausa'),
             ('bak', 'Bashkir'),
             ('mai', 'Maithili'),
             ('kok', 'Konkani '),
             ('tuk', 'Turkmen'),
             ('new', 'Newari'),
             ('sit', 'Sino-Tibetan (Other)'),
             ('frm', 'French, Middle (ca. 1300-1600)'),
             ('roa', 'Romance (Other)'),
             ('nic', 'Niger-Kordofanian (Other)'),
             ('inc', 'Indic (Other)'),
             ('pli', 'Pali'),
             ('mol', 'Moldavian'),
             ('fiu', 'Finno-Ugrian (Other)'),
             ('map', 'Austronesian (Other)'),
             ('esp', 'Esperanto'),
             ('fro', 'French, Old (ca. 842-1300)'),
             ('tag', 'Tagalog'),
             ('tut', 'Altaic (Other)'),
             ('wen', 'Sorbian (Other)'),
             ('chv', 'Chuvash'),
             ('syr', 'Syriac, Modern'),
             ('bal', 'Baluchi'),
             ('chu', 'Church Slavic'),
             ('tir', 'Tigrinya'),
             ('sun', 'Sundanese'),
             ('dra', 'Dravidian (Other)'),
             ('mni', 'Manipuri'),
             ('som', 'Somali'),
             ('paa', 'Papuan (Other)'),
             ('gla', 'Scottish Gaelic'),
             ('ban', 'Balinese'),
             ('cau', 'Caucasian (Other)'),
             ('bho', 'Bhojpuri'),
             ('gmh', 'German, Middle High (ca. 1050-1500)'),
             ('lah', 'Lahndā'),
             ('bra', 'Braj'),
             ('pra', 'Prakrit languages'),
             ('nob', 'Norwegian (Bokmål)'),
             ('yor', 'Yoruba'),
             ('zul', 'Zulu'),
             ('sah', 'Yakut'),
             ('mlt', 'Maltese'),
             ('far', 'Faroese'),
             ('ang', 'English, Old (ca. 450-1100)'),
             ('doi', 'Dogri'),
             ('kas', 'Kashmiri'),
             ('xho', 'Xhosa'),
             ('tar', 'Tatar'),
             ('mlg', 'Malagasy'),
             ('kin', 'Kinyarwanda'),
             ('bre', 'Breton'),
             ('sla', 'Slavic (Other)'),
             ('cpf', 'Creoles and Pidgins, French-based (Other)'),
             ('egy', 'Egyptian'),
             ('fri', 'Frisian'),
             ('bnt', 'Bantu (Other)'),
             ('pro', 'Provençal (to 1500)'),
             ('uig', 'Uighur'),
             ('myn', 'Mayan languages'),
             ('sco', 'Scots'),
             ('rom', 'Romani'),
             ('sai', 'South American Indian (Other)'),
             ('lus', 'Lushai'),
             ('div', 'Maldivian'),
             ('mla', 'Malagasy'),
             ('gem', 'Germanic (Other)'),
             ('fao', 'Faroese'),
             ('oss', 'Ossetic'),
             ('epo', 'Esperanto'),
             ('nso', 'Northern Sotho'),
             ('sho', 'Shona'),
             ('hbs', 'Serbo-Croatian'),
             ('akk', 'Akkadian'),
             ('lan', 'Occitan (post 1500)'),
             ('ful', 'Fula'),
             ('kha', 'Khasi'),
             ('jrb', 'Judeo-Arabic'),
             ('sso', 'Sotho'),
             ('esk', 'Eskimo languages'),
             ('fry', 'Frisian'),
             ('pap', 'Papiamento'),
             ('lug', 'Ganda'),
             ('wol', 'Wolof '),
             ('cre', 'Cree'),
             ('ber', 'Berber (Other)'),
             ('arc', 'Aramaic'),
             ('sna', 'Shona'),
             ('che', 'Chechen'),
             ('lad', 'Ladino'),
             ('ady', 'Adygei'),
             ('cop', 'Coptic'),
             ('ltz', 'Luxembourgish'),
             ('ibo', 'Igbo'),
             ('hat', 'Haitian French Creole'),
             ('que', 'Quechua'),
             ('tsn', 'Tswana'),
             ('oci', 'Occitan (post 1500)'),
             ('haw', 'Hawaiian'),
             ('nai', 'North American Indian (Other)'),
             ('mis', 'Miscellaneous languages'),
             ('tsw', 'Tswana'),
             ('nde', 'Ndebele (Zimbabwe)'),
             ('oji', 'Ojibwa'),
             ('bua', 'Buriat'),
             ('dzo', 'Dzongkha'),
             ('nya', 'Nyanja'),
             ('cor', 'Cornish'),
             ('phi', 'Philippine (Other)'),
             ('chm', 'Mari'),
             ('moh', 'Mohawk'),
             ('sot', 'Sotho'),
             ('mag', 'Magahi'),
             ('ven', 'Venda'),
             ('udm', 'Udmurt '),
             ('crp', 'Creoles and Pidgins (Other)'),
             ('cai', 'Central American Indian (Other)'),
             ('awa', 'Awadhi '),
             ('cos', 'Corsican'),
             ('nah', 'Nahuatl'),
             ('tso', 'Tsonga'),
             ('mao', 'Maori'),
             ('gez', 'Ethiopic'),
             ('ssa', 'Nilo-Saharan (Other)'),
             ('mwr', 'Marwari'),
             ('tet', 'Tetum'),
             ('kbd', 'Kabardian'),
             ('kom', 'Komi'),
             ('alg', 'Algonquian (Other)'),
             ('mkh', 'Mon-Khmer (Other)'),
             ('ssw', 'Swazi '),
             ('eth', 'Ethiopic'),
             ('syc', 'Syriac'),
             ('twi', 'Twi'),
             ('afa', 'Afroasiatic (Other)'),
             ('kar', 'Karen languages'),
             ('fur', 'Friulian'),
             ('orm', 'Oromo'),
             ('srd', 'Sardinian'),
             ('bem', 'Bemba'),
             ('btk', 'Batak'),
             ('man', 'Mandingo'),
             ('pal', 'Pahlavi'),
             ('iku', 'Inuktitut'),
             ('kaa', 'Kara-Kalpak'),
             ('cam', 'Khmer'),
             ('min', 'Minangkabau'),
             ('ava', 'Avaric'),
             ('bam', 'Bambara'),
             ('gal', 'Oromo'),
             ('nno', 'Nynorsk'),
             ('smo', 'Samoan'),
             ('abk', 'Abkhaz'),
             ('cpe', 'Creoles and Pidgins, English-based (Other)'),
             ('ewe', 'Ewe'),
             ('ceb', 'Cebuano'),
             ('ace', 'Achinese'),
             ('goh', 'Old High German'),
             ('dum', 'Dutch, Middle (ca. 1050-1350)'),
             ('him', 'Himachali'),
             ('fil', 'Filipino'),
             ('got', 'Gothic'),
             ('sux', 'Sumerian'),
             ('chr', 'Cherokee'),
             ('ndo', 'Ndonga'),
             ('shn', 'Shan'),
             ('kac', 'Kachin'),
             ('mic', 'Micmac'),
             ('gua', 'Guarani'),
             ('iba', 'Iban'),
             ('krc', 'Karachay-Balkar'),
             ('grn', 'Guarani'),
             ('taj', 'Tajik'),
             ('kaw', 'Kawi'),
             ('kon', 'Kongo'),
             ('dak', 'Dakota'),
             ('gaa', 'Gã'),
             ('kal', 'Kalâtdlisut'),
             ('swz', 'Swazi'),
             ('kik', 'Kikuyu'),
             ('cpp', 'Creoles and Pidgins, Portuguese-based (Other)'),
             ('lap', 'Sami'),
             ('run', 'Rundi'),
             ('bik', 'Bikol'),
             ('ilo', 'Iloko'),
             ('ira', 'Iranian (Other)'),
             ('zza', 'Zaza'),
             ('gsw', 'gsw'),
             ('pam', 'Pampanga'),
             ('aus', 'Australian languages'),
             ('kru', 'Kurukh'),
             ('nds', 'Low German'),
             ('srr', 'Serer'),
             ('tyv', 'Tuvinian'),
             ('ine', 'Indo-European (Other)'),
             ('mos', 'Mooré'),
             ('xal', 'Oirat'),
             ('mun', 'Munda (Other)'),
             ('hmn', 'Hmong'),
             ('iro', 'Iroquoian (Other)'),
             ('nbl', 'Ndebele (South Africa)'),
             ('lez', 'Lezgian'),
             ('kum', 'Kumyk'),
             ('kab', 'Kabyle'),
             ('kua', 'Kuanyama'),
             ('son', 'Songhai'),
             ('aym', 'Aymara'),
             ('dar', 'Dargwa'),
             ('myv', 'Erzya'),
             ('chg', 'Chagatai'),
             ('snk', 'Soninke'),
             ('cel', 'Celtic (Other)'),
             ('cho', 'Choctaw'),
             ('mus', 'Creek'),
             ('sam', 'Samaritan Aramaic'),
             ('kpe', 'Kpelle'),
             ('mak', 'Makasar'),
             ('mno', 'Manobo languages'),
             ('ath', 'Athapascan (Other)'),
             ('lin', 'Lingala'),
             ('bug', 'Bugis'),
             ('tah', 'Tahitian'),
             ('her', 'Herero'),
             ('hil', 'Hiligaynon'),
             ('khi', 'Khoisan (Other)'),
             ('sat', 'Santali'),
             ('tai', 'Tai'),
             ('ast', 'Asturian'),
             ('bas', 'Basa'),
             ('int', 'Interlingua (International Auxiliary Language Association)'),
             ('smi', 'Sami'),
             ('yue', 'Cantonese'),
             ('dyu', 'Dyula'),
             ('jpr', 'Judeo-Persian'),
             ('tig', 'Tigré'),
             ('tmh', 'Tamashek'),
             ('zap', 'Zapotec'),
             ('aka', 'Akan'),
             ('kro', 'Kru (Other)'),
             ('nog', 'Nogai'),
             ('crh', 'Crimean Tatar'),
             ('nyn', 'Nyankole'),
             ('fat', 'Fanti'),
             ('aar', 'Afar'),
             ('inh', 'Ingush'),
             ('vai', 'Vai'),
             ('loz', 'Lozi'),
             ('sme', 'Northern Sami'),
             ('art', 'Artificial (Other)'),
             ('ave', 'Avestan'),
             ('chn', 'Chinook jargon'),
             ('frs', 'East Frisian'),
             ('mad', 'Madurese'),
             ('pau', 'Palauan'),
             ('glv', 'Manx'),
             ('luo', 'Luo (Kenya and Tanzania)'),
             ('mdf', 'Moksha'),
             ('rup', 'Aromanian'),
             ('arn', 'Mapuche'),
             ('sag', 'Sango (Ubangi Creole)'),
             ('sal', 'Salishan languages'),
             ('tlh', 'Klingon'),
             ('mah', 'Marshallese'),
             ('tsi', 'Tsimshian'),
             ('ach', 'Acoli'),
             ('ada', 'Adangme'),
             ('cus', 'Cushitic (Other)'),
             ('gay', 'Gayo'),
             ('ina', 'Interlingua (International Auxiliary Language Association)'),
             ('pon', 'Ponape'),
             ('ypk', 'Yupik languages'),
             ('apa', 'Apache languages'),
             ('day', 'Dayak'),
             ('fon', 'Fon'),
             ('sem', 'Semitic (Other)'),
             ('alt', 'Altai'),
             ('del', 'Delaware'),
             ('ton', 'Tongan'),
             ('efi', 'Efik'),
             ('mnc', 'Manchu'),
             ('non', 'Old Norse'),
             ('peo', 'Old Persian (ca. 600-400 B.C.)'),
             ('war', 'Waray'),
             ('bai', 'Bamileke languages'),
             ('kam', 'Kamba'),
             ('nzi', 'Nzima'),
             ('oto', 'Otomian languages'),
             ('elx', 'Elamite'),
             ('gon', 'Gondi'),
             ('ido', 'Ido'),
             ('men', 'Mende'),
             ('nav', 'Navajo'),
             ('pag', 'Pangasinan'),
             ('fij', 'Fijian'),
             ('sao', 'Samoan'),
             ('yao', 'Yao (Africa)'),
             ('arg', 'Aragonese'),
             ('bin', 'Edo'),
             ('fan', 'Fang'),
             ('gil', 'Gilbertese'),
             ('lol', 'Mongo-Nkundu'),
             ('tog', 'Tonga (Nyasa)'),
             ('bla', 'Siksika'),
             ('cha', 'Chamorro'),
             ('chy', 'Cheyenne'),
             ('lub', 'Luba-Katanga'),
             ('rar', 'Rarotongan'),
             ('vls', 'Flemish'),
             ('din', 'Dinka'),
             ('grb', 'Grebo'),
             ('uga', 'Ugaritic'),
             ('dua', 'Duala'),
             ('kho', 'Khotanese'),
             ('krl', 'Karelian'),
             ('mwl', 'Mirandese'),
             ('nyo', 'Nyoro'),
             ('tum', 'Tumbuka'),
             ('arw', 'Arawak'),
             ('bis', 'Bislama'),
             ('chk', 'Chuukese'),
             ('cmc', 'Chamic languages'),
             ('ewo', 'Ewondo'),
             ('ijo', 'Ijo'),
             ('mas', 'Masai'),
             ('sad', 'Sandawe'),
             ('sel', 'Selkup'),
             ('tpi', 'Tok Pisin'),
             ('ale', 'Aleut'),
             ('kau', 'Kanuri'),
             ('lun', 'Lunda'),
             ('sas', 'Sasak'),
             ('tem', 'Temne'),
             ('tkl', 'Tokelauan'),
             ('arp', 'Arapaho'),
             ('car', 'Carib'),
             ('kos', 'Kusaie'),
             ('niu', 'Niuean'),
             ('sio', 'Siouan (Other)'),
             ('srn', 'Sranan'),
             ('umb', 'Umbundu'),
             ('znd', 'Zande languages'),
             ('zun', 'Zuni'),
             ('ase', 'American Sign Language'),
             ('gor', 'Gorontalo'),
             ('hmo', 'Hiri Motu'),
             ('ipk', 'Inupiaq'),
             ('lam', 'Lamba (Zambia and Congo)'),
             ('lua', 'Luba-Lulua'),
             ('nub', 'Nubian languages'),
             ('sus', 'Susu'),
             ('tiv', 'Tiv'),
             ('tli', 'Tlingit'),
             ('wal', 'Wolayta'),
             ('bat', 'Baltic (Other)'),
             ('hsb', 'Upper Sorbian'),
             ('sid', 'Sidamo'),
             ('sog', 'Sogdian'),
             ('suk', 'Sukuma'),
             ('wak', 'Wakashan languages'),
             ('eka', 'Ekajuk'),
             ('gba', 'Gbaya'),
             ('gul', 'Gullah'),
             ('kmb', 'Kimbundu'),
             ('nau', 'Nauru'),
             ('osa', 'Osage'),
             ('ter', 'Terena'),
             ('tvl', 'Tuvaluan'),
             ('yap', 'Yapese'))
         AS new_languages (id, name)
WHERE NOT EXISTS(
        SELECT 1 FROM languages WHERE languages.id = new_languages.id
    );



